export const ADD_PLACE = 'ADD_PLACE';
export const GET_PHOTOS_LOADING = 'GET_PHOTOS_LOADING';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_FAILED = 'GET_PHOTOS_FAILED';
